# Generated by Django 5.2.17 on 2026-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManuscriptSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_id', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('publication_type', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('abstract', models.TextField()),
                ('expected_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_publication_date', models.DateField(blank=True, null=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('manuscript', models.FileField(blank=True, null=True, upload_to='manuscripts/%Y/%m/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('accepted', 'Accepted'), ('editing', 'Editing'), ('formatting', 'Formatting'), ('published', 'Published'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='publication_covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
